# Generated by Django 2.2 on 2021-01-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201228_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='orderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.OrderItem'),
        ),
    ]
