# Generated by Django 2.2 on 2021-02-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210109_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/static/images/%y/%m/%d/')),
                ('title', models.CharField(max_length=150)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
