# Generated by Django 2.2 on 2021-02-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210210_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
