# Generated by Django 2.2 on 2021-08-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210825_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ProductImages',
        ),
    ]
