# Generated by Django 2.2 on 2021-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210926_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(default='roman.nadeem@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
