# Generated by Django 2.2 on 2021-10-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_shippingaddress_email'),
        ('store', '0013_auto_20210926_1044'),
    ]

    operations = [
    ]
