# Generated by Django 2.2 on 2021-10-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20211023_2003'),
        ('store', '0016_merge_20211009_0939'),
    ]

    operations = [
    ]
