version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  AfterInstall: 
    - location: scripts/install_dependencies
      timeout: 6000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 6000
      runas: ubuntu

  

