version: 0.0
os: linux
files:
  - source: /manage.py
    destination: /home/ubuntu/app

hooks:
  BeforeInstall: 
    - location: scripts/install_dependencies
      timeout: 6000
      runas: ubuntu


  

